-- Generated from lib/benefits/registry.ts via `tsx lib/seed/generate-benefit-types-sql.ts`.
-- Do not hand-edit; change the registry and regenerate instead.
insert into benefit_types (key, category, label, description, value_schema, is_comparable, is_countable, sort_order) values
  ('401k_match', 'retirement', '401(k) match', 'Employer matching formula, cap, vesting schedule, and true-up policy for the 401(k) plan.', '{"type":"object","properties":{"formula_type":{"type":"string","title":"Formula type","enum":["percent_of_employee_contribution","percent_of_salary","tiered","fixed_usd"]},"match_percent":{"type":"number","title":"Match %","x-unit":"%"},"cap_type":{"type":"string","title":"Cap type","enum":["percent_of_irs_limit","percent_of_salary","usd"]},"cap_value":{"type":"number","title":"Cap value"},"tiers":{"type":"array","title":"Tiers","items":{"type":"object","properties":{"up_to_percent_of_salary":{"type":"number","title":"Up to % of salary contributed","x-unit":"%"},"match_percent":{"type":"number","title":"Match %","x-unit":"%"}}}},"vesting_type":{"type":"string","title":"Vesting type","enum":["immediate","cliff","graded"]},"vesting_years":{"type":"number","title":"Vesting years"},"true_up":{"type":"boolean","title":"True-up offered"},"eligibility_days":{"type":"number","title":"Eligibility waiting period (days)"}}}'::jsonb, true, true, 10),
  ('mega_backdoor_roth', 'retirement', 'Mega Backdoor Roth', 'After-tax 401(k) contributions plus a conversion path to Roth, beyond the standard employee deferral limit.', '{"type":"object","properties":{"supported":{"type":"boolean","title":"Supported"},"after_tax_contributions_allowed":{"type":"boolean","title":"After-tax contributions allowed"},"after_tax_cap_percent_of_salary":{"type":"number","title":"After-tax cap (% of salary)","x-unit":"%"},"conversion_method":{"type":"string","title":"Conversion method","enum":["automatic_daily","automatic_quarterly","manual_request","in_service_withdrawal","none"]},"conversion_fee_usd":{"type":"number","title":"Conversion fee","x-unit":"$"},"recordkeeper":{"type":"string","title":"Recordkeeper"},"headroom_note":{"type":"string","title":"Headroom note"}}}'::jsonb, true, true, 20),
  ('hsa_contribution', 'retirement', 'HSA employer contribution', 'Employer seed money into a Health Savings Account for HDHP enrollees.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"annual_employee_only_usd":{"type":"number","title":"Annual contribution — employee only","x-unit":"$"},"annual_family_usd":{"type":"number","title":"Annual contribution — family coverage","x-unit":"$"},"requires_hdhp_enrollment":{"type":"boolean","title":"Requires HDHP enrollment"}}}'::jsonb, true, true, 30),
  ('health_premium', 'health', 'Health insurance premium', 'What the employer covers of monthly medical premiums.', '{"type":"object","properties":{"employer_covers_percent_employee_only":{"type":"number","title":"Employer covers % — employee only","x-unit":"%"},"employer_covers_percent_family":{"type":"number","title":"Employer covers % — family","x-unit":"%"},"monthly_employee_cost_usd_employee_only":{"type":"number","title":"Monthly employee cost — employee only","x-unit":"$"},"monthly_employee_cost_usd_family":{"type":"number","title":"Monthly employee cost — family","x-unit":"$"},"deductible_usd_individual":{"type":"number","title":"Deductible — individual","x-unit":"$"},"out_of_pocket_max_usd_individual":{"type":"number","title":"Out-of-pocket max — individual","x-unit":"$"}}}'::jsonb, true, true, 40),
  ('parental_leave', 'family', 'Parental leave', 'Paid weeks off for birthing and non-birthing parents.', '{"type":"object","properties":{"birthing_parent_weeks_paid":{"type":"number","title":"Birthing parent — weeks paid","x-unit":"weeks"},"non_birthing_parent_weeks_paid":{"type":"number","title":"Non-birthing parent — weeks paid","x-unit":"weeks"},"pay_percent":{"type":"number","title":"Pay %","x-unit":"%"},"covers_adoption_foster":{"type":"boolean","title":"Covers adoption / foster"},"tenure_required_months":{"type":"number","title":"Tenure required (months)"}}}'::jsonb, true, false, 50),
  ('fertility_benefit', 'family', 'Fertility & family-forming benefit', 'Coverage for IVF, egg/embryo freezing, surrogacy, and adoption assistance.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"lifetime_max_usd":{"type":"number","title":"Lifetime max","x-unit":"$"},"covers_ivf":{"type":"boolean","title":"Covers IVF"},"covers_egg_freezing":{"type":"boolean","title":"Covers egg/embryo freezing"},"covers_surrogacy":{"type":"boolean","title":"Covers surrogacy"},"adoption_assistance_usd":{"type":"number","title":"Adoption assistance","x-unit":"$"},"provider":{"type":"string","title":"Provider (e.g. Carrot, Progyny)"}}}'::jsonb, true, true, 60),
  ('childcare_stipend', 'family', 'Childcare stipend', 'Recurring or backup childcare support.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"annual_usd":{"type":"number","title":"Annual amount","x-unit":"$"},"backup_care_days_per_year":{"type":"number","title":"Backup care days / year"},"provider":{"type":"string","title":"Provider (e.g. Bright Horizons)"}}}'::jsonb, true, true, 70),
  ('espp', 'equity', 'Employee Stock Purchase Plan', 'Discounted purchase of company stock via payroll deduction.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"discount_percent":{"type":"number","title":"Discount %","x-unit":"%"},"lookback":{"type":"boolean","title":"Lookback provision"},"offering_period_months":{"type":"number","title":"Offering period (months)"},"contribution_cap_percent_of_salary":{"type":"number","title":"Contribution cap (% of salary)","x-unit":"%"},"holding_period_months":{"type":"number","title":"Required holding period (months)"}}}'::jsonb, true, true, 80),
  ('equity_refresh', 'equity', 'Equity refresh policy', 'Whether and how often employees receive additional equity grants after hire.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"cadence":{"type":"string","title":"Cadence","enum":["annual","biennial","performance_based","ad_hoc","none"]},"typical_vesting_years":{"type":"number","title":"Typical vesting (years)"},"notes":{"type":"string","title":"Notes"}}}'::jsonb, true, false, 90),
  ('pto_policy', 'time_off', 'PTO policy', 'Vacation day structure — accrued, fixed, or unlimited.', '{"type":"object","properties":{"policy_type":{"type":"string","title":"Policy type","enum":["accrued","fixed_days","unlimited","flexible"]},"days_per_year":{"type":"number","title":"Days per year","x-unit":"days"},"rollover_allowed":{"type":"boolean","title":"Rollover allowed"},"rollover_cap_days":{"type":"number","title":"Rollover cap (days)"},"paid_holidays":{"type":"number","title":"Paid holidays","x-unit":"days"}}}'::jsonb, true, false, 100),
  ('sabbatical', 'time_off', 'Sabbatical', 'Extended paid leave after a tenure milestone.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"tenure_required_years":{"type":"number","title":"Tenure required (years)"},"weeks_paid":{"type":"number","title":"Weeks paid","x-unit":"weeks"}}}'::jsonb, true, false, 110),
  ('education_reimbursement', 'education', 'Education / tuition reimbursement', 'Annual budget for courses, certifications, conferences, or degree programs.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"annual_cap_usd":{"type":"number","title":"Annual cap","x-unit":"$"},"covers_degree_programs":{"type":"boolean","title":"Covers degree programs"},"requires_manager_approval":{"type":"boolean","title":"Requires manager approval"}}}'::jsonb, true, true, 120),
  ('lifestyle_stipend', 'wellness', 'Lifestyle / wellness stipend', 'Recurring cash allowance for gym, wellness apps, or general lifestyle spend.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"annual_usd":{"type":"number","title":"Annual amount","x-unit":"$"},"cadence":{"type":"string","title":"Cadence","enum":["monthly","quarterly","annual"]},"eligible_spend":{"type":"string","title":"Eligible spend categories"}}}'::jsonb, true, true, 130),
  ('commuter_benefit', 'logistics', 'Commuter benefit', 'Pre-tax transit/parking accounts or direct commuter subsidies.', '{"type":"object","properties":{"offered":{"type":"boolean","title":"Offered"},"monthly_subsidy_usd":{"type":"number","title":"Monthly subsidy","x-unit":"$"},"pretax_account_available":{"type":"boolean","title":"Pre-tax account available"}}}'::jsonb, true, true, 140),
  ('life_insurance', 'health', 'Life & disability insurance', 'Employer-paid life and disability coverage.', '{"type":"object","properties":{"basic_life_multiple_of_salary":{"type":"number","title":"Basic life (× salary)"},"supplemental_life_available":{"type":"boolean","title":"Supplemental life available"},"short_term_disability_covered":{"type":"boolean","title":"Short-term disability covered"},"long_term_disability_covered":{"type":"boolean","title":"Long-term disability covered"}}}'::jsonb, true, false, 150),
  ('perk_misc', 'perks', 'Other perk', 'Escape hatch for perks that don''t fit a structured category (free subscriptions, on-site amenities, etc).', '{"type":"object","properties":{"name":{"type":"string","title":"Name"},"description":{"type":"string","title":"Description"},"est_annual_value_usd":{"type":"number","title":"Estimated annual value","x-unit":"$"},"conditions":{"type":"string","title":"Conditions"}}}'::jsonb, false, true, 160);
